In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.FloatTensor([2, 1]).view(1, 2)

In [14]:
x = Variable(x, requires_grad=True)

In [15]:
x, x.shape

(tensor([[2., 1.]], requires_grad=True), torch.Size([1, 2]))

In [16]:
y = Variable(torch.FloatTensor([[1, 2], [3, 4]]))

In [17]:
y, y.shape

(tensor([[1., 2.],
         [3., 4.]]), torch.Size([2, 2]))

In [18]:
z = torch.mm(x, y)

In [19]:
z, z.shape

(tensor([[5., 8.]], grad_fn=<MmBackward>), torch.Size([1, 2]))

In [20]:
j = torch.zeros((2, 2))

In [21]:
j, j.shape

(tensor([[0., 0.],
         [0., 0.]]), torch.Size([2, 2]))

In [22]:
z.backward(torch.FloatTensor([[1, 0]]), retain_graph=True)

In [23]:
j[:, 0] = x.grad.data

In [24]:
x.grad.zero_()

tensor([[0., 0.]])

In [25]:
z.backward(torch.FloatTensor([[0, 1]]), retain_graph=True)

In [26]:
j[:, 1] = x.grad.data

In [27]:
print('==========jacobain==========')
print('x')
print(x.data)
print('y')
print(y.data)
print('compute result')
print(z.data)
print('jacobian matrix is')
print(j)

==========jacobain==========
x
tensor([[2., 1.]])
y
tensor([[1., 2.],
        [3., 4.]])
compute result
tensor([[5., 8.]])
jacobian matrix is
tensor([[1., 2.],
        [3., 4.]])
