In [2]:
import torch
from torch.autograd import Variable
x = Variable(torch.Tensor([1]), requires_grad=True)
w = Variable(torch.Tensor([2]), requires_grad=True)
b = Variable(torch.Tensor([3]), requires_grad=True)

In [3]:
y = w * x + b
y.backward()

In [4]:
print(y)
print(x.grad)
print(w.grad)
print(b.grad)

tensor([5.], grad_fn=<ThAddBackward>)
tensor([2.])
tensor([1.])
tensor([1.])


In [5]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)
print(x)

tensor([ 0.2766, -0.4422, -1.3326], requires_grad=True)


In [6]:
y = x * 2
print(y)

tensor([ 0.5532, -0.8844, -2.6652], grad_fn=<MulBackward>)


In [7]:
y.backward(torch.FloatTensor([1, 0.1, 0.01]))
print(y)
print(x.grad)

tensor([ 0.5532, -0.8844, -2.6652], grad_fn=<MulBackward>)
tensor([2.0000, 0.2000, 0.0200])
