In [1]:
import numpy as np
import torch
from torch.autograd import Variable
from torch import nn
import matplotlib.pyplot as plt

In [2]:
def make_features(x):
    x = x.unsqueeze(1)
    return torch.cat([x ** i for i in range(1, 4)], 1)
w_target = torch.FloatTensor([0.5, 3, 2.4]).unsqueeze(1)
b_target = torch.FloatTensor([0.9])
print(w_target)
print(b_target)

tensor([[0.5000],
        [3.0000],
        [2.4000]])
tensor([0.9000])


In [3]:
def f(x):
    return x.mm(w_target) + b_target[0]

In [4]:
def get_batch(batch_size=32):
    random = torch.randn(batch_size)
    x = make_features(random)
    y = f(x)
    return Variable(x), Variable(y)

In [6]:
class PolyModel(nn.Module):
    def __init__(self):
        super(PolyModel, self).__init__()
        self.poly = nn.Linear(3, 1)
        
    def forward(self, x):
        out = self.poly(x)
        return out

In [7]:
model = PolyModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [12]:
epoch = 0
while True:
    batch_x, batch_y = get_batch()
    output = model(batch_x)
    loss = criterion(output, batch_y)
    print_loss = loss.item()
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch += 1
    if print_loss < 1e-3:
        break
print(epoch)

2


In [13]:
for each in model.parameters():
    print(each)

Parameter containing:
tensor([[0.5593, 3.0024, 2.3879]], requires_grad=True)
Parameter containing:
tensor([0.8918], requires_grad=True)
