In [1]:
import torch
from torch import nn
from torch.autograd import Variable

In [2]:
# num_word = 2, size = 5
embeds = nn.Embedding(2, 5)

In [3]:
embeds.weight

Parameter containing:
tensor([[ 0.7619, -1.9017,  0.1968, -0.4180, -0.3875],
        [-0.2599,  0.0770, -0.0947,  1.8181,  0.8811]], requires_grad=True)

In [4]:
embeds.weight.shape

torch.Size([2, 5])

In [5]:
embeds.weight.data

tensor([[ 0.7619, -1.9017,  0.1968, -0.4180, -0.3875],
        [-0.2599,  0.0770, -0.0947,  1.8181,  0.8811]])

In [6]:
embeds = nn.Embedding(100, 50)
tmp_word_embed = embeds(Variable(torch.LongTensor([50])))

In [7]:
tmp_word_embed

tensor([[-0.0845, -0.8891, -1.0796,  0.0745, -1.1091,  0.8451, -0.4896,  1.4913,
          1.7179,  0.5026,  0.7438, -1.7539,  0.8891,  1.1173, -0.7525,  0.7504,
          0.1076, -1.4749,  0.6340, -0.7398, -0.9718,  1.6951, -0.0809,  0.4603,
         -0.6932, -0.6703, -0.2971, -0.6497,  0.2502, -0.3893,  0.0588,  0.6166,
         -0.3427,  1.3456,  0.8543, -0.6153, -0.2014, -0.1637,  1.2859, -0.9479,
          0.0142, -0.2965,  0.1186, -1.2136, -0.2254, -0.6843,  1.6001, -0.4648,
         -0.4690, -0.3626]], grad_fn=<EmbeddingBackward>)

In [8]:
tmp_word_embed.shape

torch.Size([1, 50])